version: "3"

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 5000:8080
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
